### ISSUE TITLE
Decisions, decisions, decisions

### ISSUE THREAD

**Issue by fredeil** [Dualog-students/hackathon#1]
Checklist for the 2018 hackathon that is set to be from **june 27 to 28**.
So basically this is what we need to prepare before and during the hackathon, if there are any missing points, please let me know so we can fix it in time.

**Stage 1 (planning):**
- [x] Schedule hackathon
- [x] Find a good focus area (narrow down choices)
- [x] Define reward
- [x] Organize reward
- [x] Define gifts (stickers, t-shirts etc.)
- [x] Organize gifts

**Stage 2 (pre-hackathon):**
- [x] Order pizza, drinks for the days
- [x] Print out voting cards (no app this time)
- [x] Acquire lots of pens for voting
- [x] Purchase confetti & other party materials
- [x] Set up projector (or use the kitchen screen)

**Stage 3 (first day of hackathon):**
- [x] Kick-off event (introduce hacakthon and information etc.)
- [x] Make teams (teams should have at least one tech person)
- [x] Have a grill-party if the weather allows it

**Stage 4 (second day of hackathon):**
- [x] Remind everyone that they have one hour left
- [x] Stop people from working after deadline
- [x] Define order of presentations
- [x] Hand out & collect voting cards
- [x] Celebrate and have a good time

**Stage 5 (aftermath):**
- [x] Document open ideas for the summer students (maybe they can work on something)
- [x] Collect photos and videos
